### ISSUE TITLE
Crashlytics reports that the UpdateChecker crashes

### ISSUE THREAD

**Issue by falcon4ever** [pietrorampini/UpdateChecker#118]
Hi,

thanks for writing this great update checker lib! It has been very useful in my apps.

There seems to be an issue that shows up every time there is a new release. For some reason I get these crash reports (from Crashlytics) in the logs (haven't been able to reproduce a crash on my own devices):

Error:
**Dialog.java line 82
com.rampo.updatechecker.notice.Dialog.show**

Logcat:
`android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@43347b38 is not valid; is your activity running?
       at android.view.ViewRootImpl.setView(ViewRootImpl.java:764)
       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:278)
       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
       at android.app.Dialog.show(Dialog.java:289)
       at com.rampo.updatechecker.notice.Dialog.show(Dialog.java:82)
       at com.rampo.updatechecker.UpdateChecker.showDialog(UpdateChecker.java:289)
       at com.rampo.updatechecker.UpdateChecker.foundUpdateAndShowIt(UpdateChecker.java:198)
       at com.rampo.updatechecker.UpdateChecker.versionDownloadableFound(UpdateChecker.java:141)
       at com.rampo.updatechecker.ASyncCheck.onPostExecute(ASyncCheck.java:137)
       at com.rampo.updatechecker.ASyncCheck.onPostExecute(ASyncCheck.java:44)
       at android.os.AsyncTask.finish(AsyncTask.java:632)
       at android.os.AsyncTask.access$600(AsyncTask.java:177)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5579)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
       at dalvik.system.NativeStart.main(NativeStart.java)`

Screenshot:
![fabric-2 1 6](https://cloud.githubusercontent.com/assets/480019/9120488/829d6440-3c4a-11e5-8c0b-0b633d746a3b.png)

Used version:
UpdateChecker 2.1.6

Implementation:
The updater code is placed in a Activity/onCreate like this:

UpdateChecker checker = new UpdateChecker(this);
checker.start();

**Comment by rampo** [comment]
Hi, thank you for the report.

This issue doesn't cause a crash, isn't it? The code is placed in a try/catch block. As you can see [here](https://github.com/rampo/UpdateChecker/blob/509eabd2745166bbb190c641a523628328546c6f/library/src/main/java/com/rampo/updatechecker/notice/Dialog.java#L88) the WindowManager.BadTokenException is included. I think this happens when the library tries to show the Dialog but the activity has already been closed. See App in Focus at only 10% in the Crashlytics report

**Comment by falcon4ever** [comment]
Hi Rampo,

thanks for the response!

I actually don't know if it crashes the app as from my own testing I haven't been able to make the updater crash. It's just that with the app releases I made so far, I see these same reports coming in from Crashlytics.

Yea, I'm actually wondering if it might be Crashlytics that is logging the "Fatal Exceptions" as a "Crash". Not sure if there is something that can be done about it since you've already put it in a try/catch block.
